trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroupName: 'lewis-mcleancouk'
  templateFile: 'infra/main.bicep'
  azureServiceConnection: 'lewis-new-website'

stages:
  - stage: Test
    displayName: Lint bicep code
    jobs:
      job: Test
      steps:
        script: |
          az bicep build --file templateFile

  - stage: Build
    displayName: Build bicep code
    jobs: 
      job: Build
      steps:
        task: AzureCLI@2
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version

